setwd('D:/Projects/datasciencecoursera/ExploratoryDataAnalysis/Project1')
source('LoadData.R')

png('Plot4.png', width=480, height=480, units="px")
par(mfrow=c(2, 2))
plot(data$Time, data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(data$Time, data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(data$Time, data$Sub_metering_1, legend="Sub_metering_1", type="l", xlab="", ylab="Energy sub metering")
lines(data$Time, data$Sub_metering_2, type="l", col="red")
lines(data$Time, data$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "blue", "red"), lty=rep("solid", 3))
plot(data$Time, data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
